# -*- coding: utf-8 -*-
"""smartmoney.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJ-KBuT0f5DpWssbS1qC76ecd6XZu6Re
"""

import yfinance as yf
import pandas as pd
import numpy as np
import warnings
from datetime import datetime
import requests

# 🧠 AI Çekirdeği
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Gereksiz uyarıları gizle
warnings.filterwarnings("ignore")

# ============================================================
# 🏛️ V13: TITAN PROD CONFIGURATION (OPTIMIZED)
# ============================================================
CONFIG = {
    # --- 1. OPTİMİZE EDİLMİŞ PARAMETRELER (LAB SONUÇLARI) ---
    "EMA_TREND": 20,                  # Lab sonucu: En güvenli trend
    "ATR_MULT": 2.0,                  # Lab sonucu: En ideal stop marjı
    "TRAILING_PCT": 0.05,             # %5 İzleyen Stop (Kar koruma)

    # --- 2. GÜVENLİK DUVARI (Safety First) ---
    "MIN_MARKET_CAP": 50_000_000_000, # 50 Milyar TL (Manipülasyon Engeli)
    "MIN_LIQUIDITY": 100_000_000,     # 100 Milyon TL Günlük Hacim

    # --- 3. SMART MONEY (Akıllı Para) ---
    "SQUEEZE_THRESHOLD": 0.85,        # Sıkışma
    "DRYNESS_THRESHOLD": 0.80,        # Kuruma
    "STABILITY_THRESHOLD": 1.5,       # Stabilite

    # --- 4. AI (Machine Learning) ---
    "AI_HORIZON": 5,                  # 5 Günlük Tahmin
    "BACKTEST_DAYS": 120              # 6 Aylık Kanıt Süresi
}

# HEDEF LİSTE (BIST 100 Karması)
TICKERS = [
    "AEFES.IS", "AGHOL.IS", "AKBNK.IS", "AKSA.IS", "ALARK.IS", "ARCLK.IS",
    "ASELS.IS", "ASTOR.IS", "BIMAS.IS", "BRSAN.IS", "CCOLA.IS", "CIMSA.IS",
    "CWENE.IS", "DOAS.IS", "DOHOL.IS", "EGEEN.IS", "EKGYO.IS", "ENJSA.IS",
    "ENKAI.IS", "EREGL.IS", "EUPWR.IS", "FROTO.IS", "GARAN.IS", "GESAN.IS",
    "GUBRF.IS", "HALKB.IS", "HEKTS.IS", "ISCTR.IS", "ISMEN.IS", "KCHOL.IS",
    "KONTR.IS", "KOZAL.IS", "KRDMD.IS", "MGROS.IS", "MIATK.IS", "ODAS.IS",
    "OTKAR.IS", "OYAKC.IS", "PETKM.IS", "PGSUS.IS", "SAHOL.IS", "SASA.IS",
    "SISE.IS", "SOKM.IS", "TAVHL.IS", "TCELL.IS", "THYAO.IS", "TKFEN.IS",
    "TOASO.IS", "TSKB.IS", "TTKOM.IS", "TTRAK.IS", "TUPRS.IS", "ULKER.IS",
    "VAKBN.IS", "VESTL.IS", "YKBNK.IS", "YEOTK.IS", "XU100.IS"
]

# ============================================================
# 🛠️ FEATURE ENGINEERING: SMART MONEY DEDEKTÖRÜ
# ============================================================
def calculate_features(df):
    df = df.copy()

    # 1. Trend (EMA 20 - Optimize Edilmiş)
    df['EMA_Trend'] = df['Close'].ewm(span=CONFIG['EMA_TREND'], adjust=False).mean()
    df['Trend_Dist'] = (df['Close'] - df['EMA_Trend']) / df['EMA_Trend']

    # 2. Bollinger Sıkışması (Squeeze)
    df['Mid'] = df['Close'].rolling(20).mean()
    df['Std'] = df['Close'].rolling(20).std()
    df['BB_Width'] = ((df['Mid'] + 2*df['Std']) - (df['Mid'] - 2*df['Std'])) / df['Mid']
    df['Squeeze_Idx'] = df['BB_Width'] / df['BB_Width'].rolling(120).mean()

    # 3. Hacim Kuruması (Dryness)
    df['Vol_Dry_Idx'] = df['Volume'].rolling(5).mean() / df['Volume'].rolling(50).mean()

    # 4. Stabilite (Kontrollü Süzülme)
    tr = pd.concat([df['High'] - df['Low'], (df['High'] - df['Close'].shift(1)).abs(), (df['Low'] - df['Close'].shift(1)).abs()], axis=1).max(axis=1)
    df['ATR'] = tr.ewm(span=14, adjust=False).mean()
    body_size = (df['Close'] - df['Open']).abs()
    df['Stability_Idx'] = body_size.rolling(10).mean() / df['ATR']

    # 5. Hacim Şiddeti (Intensity)
    df['Intensity'] = df['Volume'] / df['Volume'].rolling(50).mean()

    # 6. RSI (AI Girdisi)
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).ewm(alpha=1/14, adjust=False).mean()
    loss = (-delta.where(delta < 0, 0)).ewm(alpha=1/14, adjust=False).mean()
    df['RSI'] = 100 - (100 / (1 + (gain/loss)))

    return df.dropna()

# ============================================================
# 🧠 AI ENGINE: GELECEĞİ TAHMİN ET
# ============================================================
def get_ai_prediction(df):
    """
    Optimize edilmiş parametrelerle eğitilen Lojistik Regresyon.
    Hedef: Gelecek 5 günde %2 üzeri net getiri.
    """
    data = df.copy()

    # Target: 5 gün sonra fiyat bugünden %2 yüksek mi?
    data['Target'] = (data['Close'].shift(-CONFIG['AI_HORIZON']) > data['Close'] * 1.02).astype(int)
    data = data.dropna()

    if len(data) < 150: return 50.0

    # Model Girdileri
    features = ['Squeeze_Idx', 'Vol_Dry_Idx', 'Stability_Idx', 'Trend_Dist', 'Intensity', 'RSI']
    X = data[features]
    y = data['Target']

    # Ölçeklendirme
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Eğitim (Data Leakage'i önlemek için son 5 günü hariç tut)
    model = LogisticRegression(class_weight='balanced', solver='liblinear', random_state=42)
    try:
        model.fit(X_scaled[:-5], y[:-5])
        # Tahmin
        current_features = X_scaled[-1].reshape(1, -1)
        prob = model.predict_proba(current_features)[0][1]
        return prob * 100
    except:
        return 50.0

# ============================================================
# 🧪 BACKTEST ENGINE: KANIT SORGULA
# ============================================================
def run_optimized_backtest(df):
    """
    V12.1'de bulduğumuz EN İYİ parametreler (EMA 20, ATR 2.0) ile test eder.
    """
    data = df.tail(CONFIG['BACKTEST_DAYS']).copy()
    balance = 10000.0
    position = 0.0
    entry_price = 0.0
    highest_price = 0.0

    for i in range(len(data)):
        row = data.iloc[i]
        price = row['Close']

        # AL: Trend yukarı + Stabil + Hacim var
        if position == 0:
            if row['Close'] > row['EMA_Trend'] and row['Intensity'] > 1.0:
                position = balance / price
                entry_price = price
                balance = 0
                highest_price = price

        # SAT: Trailing Stop (%5 Optimize Edilmiş)
        elif position > 0:
            if price > highest_price: highest_price = price

            stop_price = highest_price * (1 - CONFIG['TRAILING_PCT'])
            # Ekstra güvenlik: ATR Stop
            atr_stop = entry_price - (row['ATR'] * CONFIG['ATR_MULT'])

            final_stop = max(stop_price, atr_stop)

            if price < final_stop or price < row['EMA_Trend']:
                balance = position * price
                position = 0

    if position > 0: balance = position * data.iloc[-1]['Close']
    return (balance - 10000) / 10000 * 100
def send_telegram(msg):
    url = f"https://api.telegram.org/bot8396968001:AAEKIdyqNIEWMyGwbVzBonzlDF9kCd3D9DA/sendMessage"
    payload = {
        "chat_id": -5050366031,
         "text": f"<pre>{msg}</pre>",
         "parse_mode": "HTML"
         }
    requests.post(url, data=payload)

# ============================================================
# 🚀 TITAN PROD RUNNER
# ============================================================
def run_titan_prod():
    message = ""
    message += f"\n🏛️  V13: TITAN PROD (OPTIMIZED) | {datetime.now().strftime('%d-%m-%Y')}"
    message += f"\n🔬  Parametreler: EMA-{CONFIG['EMA_TREND']} | Stop: ATR x {CONFIG['ATR_MULT']} | Trail: %{CONFIG['TRAILING_PCT']*100:.0f}"
    message += f"\n🛡️  Güvenlik: >50 Milyar TL Market Cap"
    message += "\n⏳ Büyük veri işleniyor (AI Learning + Smart Money Analysis)..."

    raw_data = yf.download(TICKERS, period="2y", group_by='ticker', auto_adjust=False, progress=False)
    results = []

    for t in TICKERS:
        if t == "XU100.IS": continue

        try:
            # 1. MARKET CAP FİLTRESİ (Güvenlik)
            try:
                info = yf.Ticker(t).fast_info
                mcap = info['market_cap']
                if mcap < CONFIG['MIN_MARKET_CAP']: continue
            except: continue

            # 2. VERİ HAZIRLIĞI
            df = raw_data[t].copy().dropna()
            if len(df) < 200: continue

            df = calculate_features(df)
            last = df.iloc[-1]

            # Likidite Filtresi
            if last['Close'] * last['Volume'] < CONFIG['MIN_LIQUIDITY']: continue

            # Trend Filtresi (EMA 20 Altı Yasak)
            if last['Close'] < last['EMA_Trend']: continue

            # 3. SMART MONEY PUANLAMA (Kalite Kontrol)
            sm_score = 0
            reasons = []

            if last['Squeeze_Idx'] < CONFIG['SQUEEZE_THRESHOLD']:
                sm_score += 1; reasons.append("SIKIŞMA")
            if last['Vol_Dry_Idx'] < CONFIG['DRYNESS_THRESHOLD']:
                sm_score += 1; reasons.append("KURUMA")
            if last['Stability_Idx'] < CONFIG['STABILITY_THRESHOLD']:
                sm_score += 1; reasons.append("STABİL")
            if last['Intensity'] > 1.5:
                sm_score += 1; reasons.append("🔥 HACİM ŞOKU")

            # 4. AI & BACKTEST
            ai_prob = get_ai_prediction(df)
            roi = run_optimized_backtest(df)

            # 5. KAYIT
            results.append({
                "Hisse": t.replace(".IS",""),
                "Fiyat": last['Close'],
                "MCap_Mlr": mcap / 1e9,
                "SM_Kalite": sm_score,   # Max 4
                "AI_Prob": ai_prob,      # % Olasılık
                "ROI_Kanit": roi,        # % Kanıt
                "Etiketler": " + ".join(reasons) if reasons else "TREND TAKİBİ",
                "Stop": last['Close'] - (last['ATR'] * CONFIG['ATR_MULT'])
            })

        except Exception as e: continue

    if not results:
        print("❌ Kriterlere uygun hisse bulunamadı.")
        return

    # SIRALAMA: (Smart Money Kalitesi > AI Olasılığı > ROI Kanıtı)
    df_res = pd.DataFrame(results).sort_values(["SM_Kalite", "AI_Prob"], ascending=[False, False])

    message += f"\n📊 TİTAN PROD NİHAİ LİSTE"
    message += f"\n{'HİSSE':<6} {'FİYAT':<9} {'SM_QLTY':<8} {'AI_PROB':<4} {'(SMART MONEY)':<32} {'STOP':<6}"

    for _, row in df_res.head(30).iterrows():
        # Görselleştirmeler
        ai_str = f"%{row['AI_Prob']:.1f}"
        roi_str = f"%{row['ROI_Kanit']:.1f}"
        sm_bar = "⭐" * int(row['SM_Kalite'])

        # Yapay Zeka Rengi (Konsolda metin olarak)
        if row['AI_Prob'] > 65: ai_tag = " (GÜÇLÜ)"
        else: ai_tag = ""

        # ROI Kanıtı Kötüyse Uyar
        if row['ROI_Kanit'] < 0: roi_str += " ⚠️"
        message += (f"\n{row['Hisse']:<6} "f"{row['Fiyat']:<7.2f} "f"{sm_bar:<4} "f"{ai_str:<6} "f"{row['Etiketler'][:18]:<18} "f"{row['Stop']:<7.2f}")


    message += "\nℹ️  SM_QLTY: ⭐⭐⭐⭐ = Sıkışma + Kuruma + Stabilite + Hacim Patlaması (Nadir ve Değerli)."
    message += "\nℹ️  AI_PROB: Yapay Zeka'nın bu teknik verilere dayanarak 'Yükseliş' tahmini."
    message += "\nℹ️  ROI(KANIT): Bu strateji son 6 ayda bu hissede para kazandırdı mı?"
    send_telegram(message)

if __name__ == "__main__":
    run_titan_prod()